### ISSUE TITLE
APEx benchmarks: add metrics

### ISSUE THREAD

**Issue by JeroenVerstraelen** [ESA-APEx/apex_algorithms#7]
Add metrics to the initial benchmark tests.

- For each benchmark, extract metrics using openEO 
  - Preferably relative metrics: 
     - cost per produced sqkm
     - cost per input pixel
  - Timing related metrics
  - Discuss which other metrics we can include 
- Upload results as geoparquet file to S3 object storage
  - Which endpoint/bucket? 

Goal: partitioned parquet file (partitioned on: time based, benchmarking scenarios)

**Comment by soxofaan** [comment]
added some docs at https://github.com/ESA-APEx/apex_algorithms/blob/main/docs/benchmarking.md

**Comment by soxofaan** [comment]
most important aspect to still cover under this ticket: 
- [ ] record collected metrics in a parquet file on S3

**Comment by soxofaan** [comment]
First results from pushing some metrics as parquet to S3:

![image](https://github.com/user-attachments/assets/117e688b-4928-41dc-b016-4c99a3016c72)

**Comment by soxofaan** [comment]
and now with unrolling the usage stats:
![image](https://github.com/user-attachments/assets/4e5d58eb-5a7a-415d-ad9f-8ce3f87dcc72)

**Comment by soxofaan** [comment]
merged PR #26 which covers the part about partitioned parquet files on S3

**Comment by soxofaan** [comment]
Ok I think it's time to close this ticket.
There were quite some aspects to it and I'm still unsure about some parts of the current approach, so this feels mostly like a proof of concept solution. Also, not everything of this ticket's original requirements are met, but those were "TBD" anyway.

Some details and discussion about this PoC:
- benchmarks are implemented as pytest test suite
- metrics are collected through a pytest fixture `track_metric` provided by pytest plugin `apex_algorithm_qa_tools.pytest.pytest_track_metrics`. Currently collected metrics/properties:
    - scenario_id, job_id
    - job costs
    - job's usage metrics (e.g. usage:cpu:cpu-seconds, usage:memory:mb-seconds)
    - test info: outcome (passed/failed), start time, duration
- these metrics are written in parquet format to S3 (bucket "APEx-benchmarks"), in a folder structure starting at "metrics/v1/metrics.parquet"
    - current partitioning is based on month of the benchmark run, e.g. folder "metrics/v1/metrics.parquet/2024-08/"
    - data is written using "pyarrow.parquet.write_to_dataset" using `existing_data_behavior=overwrite_or_ignore` mode: there is no appending to an existing file, but each run results in a separate file on S3 (e.g. "metrics/v1/metrics.parquet/2024-08/gh-10612685244-0.parquet"). 
        - advantage: no concurrency issue or other risks related to file appending (locking/synchronization, risk of corrupting the whole data set with a bad write, ...).
        - disadvantage: will result in overly partitioned data set (lot of small files), so this might require some reconsideration in the longer term (or some workflow where small files are compiled together to larger ones)
- As illustration, a view of currently recorded metrics: ![image](https://github.com/user-attachments/assets/1382713b-c836-4ec9-8be5-117047d94624)
- Note that with current setup it is possible to download individual parquet files without credentials, but I did not manage yet to load the larger data set (multiple partitions) without credentials. I guess this is because of lack of S3 dir/file listing permissions. Need more investigation
